name: Pre-commit checks
on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
    branches:
      - dev
      - main

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Check Pull Request Title
        uses: Slashgear/action-check-pr-title@main
        with:
          regexp: '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(!?)(:)\s{1}([\w,\W,:]+)'
      - name: List of Changed Files
        id: files
        uses: jitterbit/get-changed-files@master
      - name: Checking Changed Files
        shell: bash
        run: |
          echo "Changed files"
          echo ${{ steps.files.outputs.all }}
          echo "Github Client version"
          echo $(gh --version)
      - name: Pre-Commit Checks
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          echo "Running pre-commit scans:"
          pre-commit run -v --files ${{ steps.files.outputs.all }}
        shell: bash
